spring.application.name=backend
server.port=8080

mqtt.url=tcp://localhost:1883
mqtt.client-id=scemas-backend
mqtt.topic=scemas/stations/batch/telemetry

spring.cloud.gcp.project-id=scemas-8d33a
spring.cloud.gcp.firestore.project-id=scemas-8d33a
spring.cloud.gcp.credentials.location=classpath:scemasFirbaseKey.json